// This file is auto-generated by @hey-api/openapi-ts

export { type Options, tonarisHello } from './sdk.gen';
export type { ClientOptions, TonarisHelloData, TonarisHelloResponse, TonarisHelloResponses } from './types.gen';
