// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type TonarisHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/hello';
};

export type TonarisHelloResponses = {
    /**
     * Ok
     */
    200: string;
};

export type TonarisHelloResponse = TonarisHelloResponses[keyof TonarisHelloResponses];
